### ISSUE TITLE
Vypisovat datum před každým záznamem

### ISSUE THREAD

**Issue by zbycz** [xjacka/github-time-grabber#2]
čau,

chtěl jsem to teď použít pro kotrolu za minulý měsíc, ale hodilo by se před každým záznem vidět datum (a potažmo číslo issue).

Tipuju to přidat někam sem? https://github.com/xjacka/github-time-grabber/blob/master/src/main/scala/xjacka/Main.scala#L69-L77

Ale vlastně moc nevím kam a jestli to je easy? :-)

Dík
P.

**Comment by xjacka** [comment]
Datum přidat půjde, to bude v pohodně, ale číslo issue bude asi problém, protože v dotazu který používám (https://developer.github.com/v3/issues/comments/#list-comments-in-a-repository) ho github nevrací.

**Comment by zbycz** [comment]
Možná vyparsovat z `html_url` ? :-)

Ale to issue není tak důležité - datum je pro kontrolu výpisu podstatnější.
A myslím že jde o datum created..

**Comment by xjacka** [comment]
datum přidán.

**Comment by zbycz** [comment]
Moc díky :panda_face:
